image: rlancer/gcloud-node:1.0.2


deploy_production:
  stage: deploy
  environment: Production
  only:
  - master
  script:
  - npm install
  - npm run build
  - pip install -t lib -r requirements.txt
  - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gcloud --quiet --project $PROJECT_ID app deploy app.yaml
deploy_staging:
  stage: deploy
  environment: Staging
  only:
  - staging
  script:
  - npm install
  - npm run build
  - pip install -t lib -r requirements.txt
  - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gcloud --quiet --project $PROJECT_ID app deploy staging-app.yaml

after_script:
- rm /tmp/$CI_PIPELINE_ID.json